In [ ]:
# Import Libraries
import pandas as pd
import sqlite3

In [ ]:
# Read the Excel file using pandas
url = (r"C:\Users\harin\OneDrive\Desktop\TRAFFIC _CRASH PROJECT\Traffic_CrashesData.csv")
df = pd.read_csv(url)

In [6]:
pd.set_option('display.max_columns', None)
df.head()

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,ROADWAY_SURFACE_COND,ROAD_DEFECT,REPORT_TYPE,CRASH_TYPE,DAMAGE,DATE_POLICE_NOTIFIED,PRIM_CONTRIBUTORY_CAUSE,SEC_CONTRIBUTORY_CAUSE,STREET_NO,STREET_DIRECTION,STREET_NAME,BEAT_OF_OCCURRENCE,NUM_UNITS,MOST_SEVERE_INJURY,INJURIES_TOTAL,INJURIES_FATAL,INJURIES_INCAPACITATING,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date,year
0,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...,01/14/2025 12:25:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,SNOW OR SLUSH,NO DEFECTS,ON SCENE,NO INJURY / DRIVE AWAY,"$501 - $1,500",01/14/2025 12:38:00 PM,IMPROPER TURNING/NO SIGNAL,IMPROPER OVERTAKING/PASSING,6352,N,SHERIDAN RD,2433.0,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,12,3,1,41.997808,-87.655770,POINT (-87.655770494712 41.997807727633),2025-01-14 12:25:00,2025
1,027b0b4c21460d3441fd83929abb9673c6fc0c7d575675...,05/23/2025 09:30:00 AM,30,STOP SIGN/FLASHER,UNKNOWN,UNKNOWN,DAYLIGHT,TURNING,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NOT ON SCENE (DESK REPORT),NO INJURY / DRIVE AWAY,"OVER $1,500",05/27/2025 10:40:00 AM,IMPROPER OVERTAKING/PASSING,IMPROPER OVERTAKING/PASSING,3555,N,WESTERN AVE,1921.0,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,9,6,5,41.946529,-87.688106,POINT (-87.688106391039 41.946529480518),2025-05-23 09:30:00,2025
2,04d91dffc94f677358ca47056921ba5c4224320df27ed4...,04/05/2025 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,UNKNOWN,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,NO INJURY / DRIVE AWAY,"OVER $1,500",04/05/2025 09:23:00 PM,UNABLE TO DETERMINE,UNABLE TO DETERMINE,1005,N,DRAKE AVE,1121.0,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,1.0,0.0,20,7,4,41.899325,-87.715074,POINT (-87.715074373867 41.899324573751),2025-04-05 20:00:00,2025
3,0b5603954d84b7341c7cad4f570ea039e85919f3750ccb...,05/23/2025 09:15:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,INJURY AND / OR TOW DUE TO CRASH,$500 OR LESS,05/23/2025 09:16:00 AM,UNABLE TO DETERMINE,UNABLE TO DETERMINE,2901,W,DIVISION ST,1211.0,2,NONINCAPACITATING INJURY,1.0,0.0,0.0,1.0,0.0,2.0,0.0,9,6,5,41.902793,-87.699412,POINT (-87.699412181285 41.902792968177),2025-05-23 09:15:00,2025
4,00bce77960c2faa2a8782a8cac1d6e5715802d6c072a08...,01/14/2025 08:00:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,REAR END,FOUR WAY,STRAIGHT AND LEVEL,WET,NO DEFECTS,NOT ON SCENE (DESK REPORT),NO INJURY / DRIVE AWAY,"OVER $1,500",01/14/2025 08:45:00 AM,FOLLOWING TOO CLOSELY,FOLLOWING TOO CLOSELY,4001,W,111TH ST,2211.0,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,8,3,1,41.691207,-87.720555,POINT (-87.720554863466 41.691206664451),2025-01-14 08:00:00,2025

In [35]:
df.shape

(660934, 39)

In [36]:
df.tail()

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date,year
660929,5ff5b050ae2079df6addca8431c1bd6e381432ff72ff43...,10/18/2025 11:42:00 AM,35,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLOUDY/OVERCAST,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,11,7,10,41.938537,-87.835965,POINT (-87.835965097138 41.938536628877),2025-10-18 11:42:00,2025
660930,7a7963ac15a38f3cf7549397dd053fd7612dd5194de280...,10/18/2025 03:50:00 AM,35,NO CONTROLS,NO CONTROLS,RAIN,DARKNESS,FIXED OBJECT,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,3,7,10,41.899200,-87.618841,POINT (-87.618840672611 41.8992002546),2025-10-18 03:50:00,2025
660931,84e546c12fd8fd78ae4e2dc26fdb02d6e8f6c4c92be450...,10/18/2025 05:08:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,5.0,0.0,17,7,10,41.848081,-87.675881,POINT (-87.675881338024 41.848080595588),2025-10-18 17:08:00,2025
660932,8237045757e7fed5adfb450bd7c8472e28a61d322f86bb...,10/19/2025 01:50:00 AM,30,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,REAR TO FRONT,NOT DIVIDED,STRAIGHT AND LEVEL,...,5.0,0.0,1,1,10,41.949157,-87.648527,POINT (-87.648526617888 41.949157243366),2025-10-19 01:50:00,2025
660933,ede74fa6fd507334cd0415d3d53deb535d27d23523cd38...,06/23/2023 04:30:00 PM,30,UNKNOWN,UNKNOWN,UNKNOWN,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,16,6,6,42.004564,-87.709200,POINT (-87.709200383599 42.004564031467),2023-06-23 16:30:00,2023

In [6]:
df.columns

Index(['CRASH_RECORD_ID', 'CRASH_DATE', 'POSTED_SPEED_LIMIT',
       'TRAFFIC_CONTROL_DEVICE', 'DEVICE_CONDITION', 'WEATHER_CONDITION',
       'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE',
       'ALIGNMENT', 'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'REPORT_TYPE',
       'CRASH_TYPE', 'DAMAGE', 'DATE_POLICE_NOTIFIED',
       'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO',
       'STREET_DIRECTION', 'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'NUM_UNITS',
       'MOST_SEVERE_INJURY', 'INJURIES_TOTAL', 'INJURIES_FATAL',
       'INJURIES_INCAPACITATING', 'INJURIES_NON_INCAPACITATING',
       'INJURIES_REPORTED_NOT_EVIDENT', 'INJURIES_NO_INDICATION',
       'INJURIES_UNKNOWN', 'CRASH_HOUR', 'CRASH_DAY_OF_WEEK', 'CRASH_MONTH',
       'LATITUDE', 'LONGITUDE', 'LOCATION', 'date', 'year'],
      dtype='object')

In [38]:
df.dtypes

CRASH_RECORD_ID                   object
CRASH_DATE                        object
POSTED_SPEED_LIMIT                 int64
TRAFFIC_CONTROL_DEVICE            object
DEVICE_CONDITION                  object
WEATHER_CONDITION                 object
LIGHTING_CONDITION                object
FIRST_CRASH_TYPE                  object
TRAFFICWAY_TYPE                   object
ALIGNMENT                         object
ROADWAY_SURFACE_COND              object
ROAD_DEFECT                       object
REPORT_TYPE                       object
CRASH_TYPE                        object
DAMAGE                            object
DATE_POLICE_NOTIFIED              object
PRIM_CONTRIBUTORY_CAUSE           object
SEC_CONTRIBUTORY_CAUSE            object
STREET_NO                          int64
STREET_DIRECTION                  object
STREET_NAME                       object
BEAT_OF_OCCURRENCE               float64
NUM_UNITS                          int64
MOST_SEVERE_INJURY                object
INJURIES_TOTAL                   float64
INJURIES_FATAL                   float64
INJURIES_INCAPACITATING          float64
INJURIES_NON_INCAPACITATING      float64
INJURIES_REPORTED_NOT_EVIDENT    float64
INJURIES_NO_INDICATION           float64
INJURIES_UNKNOWN                 float64
CRASH_HOUR                         int64
CRASH_DAY_OF_WEEK                  int64
CRASH_MONTH                        int64
LATITUDE                         float64
LONGITUDE                        float64
LOCATION                          object
date                              object
year                               int64
dtype: object

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660934 entries, 0 to 660933
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH_RECORD_ID                660934 non-null  object
 1   CRASH_DATE                     660934 non-null  object
 2   POSTED_SPEED_LIMIT             660934 non-null  int64
 3   TRAFFIC_CONTROL_DEVICE         660934 non-null  object
 4   DEVICE_CONDITION               660934 non-null  object
 5   WEATHER_CONDITION              660934 non-null  object
 6   LIGHTING_CONDITION             660934 non-null  object
 7   FIRST_CRASH_TYPE               660934 non-null  object
 8   TRAFFICWAY_TYPE                660934 non-null  object
 9   ALIGNMENT                      660934 non-null  object
 10  ROADWAY_SURFACE_COND           660934 non-null  object
 11  ROAD_DEFECT                    660934 non-null  object
 12  REPORT_TYPE                    660934 non-null  object
 13  CRASH_TYPE                     660934 non-null  object
 14  DAMAGE                         660934 non-null  object
 15  DATE_POLICE_NOTIFIED           660934 non-null  object
 16  PRIM_CONTRIBUTORY_CAUSE        660934 non-null  object
 17  SEC_CONTRIBUTORY_CAUSE         660934 non-null  object
 18  STREET_NO                      660934 non-null  int64
 19  STREET_DIRECTION               660934 non-null  object
 20  STREET_NAME                    660934 non-null  object
 21  BEAT_OF_OCCURRENCE             660934 non-null  float64
 22  NUM_UNITS                      660934 non-null  int64
 23  MOST_SEVERE_INJURY             660934 non-null  object
 24  INJURIES_TOTAL                 660934 non-null  float64
 25  INJURIES_FATAL                 660934 non-null  float64
 26  INJURIES_INCAPACITATING        660934 non-null  float64
 27  INJURIES_NON_INCAPACITATING    660934 non-null  float64
 28  INJURIES_REPORTED_NOT_EVIDENT  660934 non-null  float64
 29  INJURIES_NO_INDICATION         660934 non-null  float64
 30  INJURIES_UNKNOWN               660934 non-null  float64
 31  CRASH_HOUR                     660934 non-null  int64
 32  CRASH_DAY_OF_WEEK              660934 non-null  int64
 33  CRASH_MONTH                    660934 non-null  int64
 34  LATITUDE                       660934 non-null  float64
 35  LONGITUDE                      660934 non-null  float64
 36  LOCATION                       660934 non-null  object
 37  date                           660934 non-null  object
 38  year                           660934 non-null  int64
dtypes: float64(10), int64(7), object(22)
memory usage: 196.7+ MB

# Database Connection

In [ ]:
# Create a Database in SQLite
conn_sqlite = sqlite3.connect("traffic_crash.sqlite")  # Creates a local database file
cursor = conn_sqlite.cursor()
print("SQLite connection established!")

SQLite connection established!

In [ ]:
# Create a Table in SQLite
cursor.execute("""
    CREATE TABLE IF NOT EXISTS crash_data (
        CRASH_RECORD_ID TEXT,
        CRASH_DATE TEXT,
        POSTED_SPEED_LIMIT BIGINT,
        TRAFFIC_CONTROL_DEVICE TEXT,
        DEVICE_CONDITION TEXT,
        WEATHER_CONDITION TEXT,
        LIGHTING_CONDITION TEXT,
        FIRST_CRASH_TYPE TEXT,
        TRAFFICWAY_TYPE TEXT,
        ALIGNMENT TEXT,
        ROADWAY_SURFACE_COND TEXT,
        ROAD_DEFECT TEXT,
        REPORT_TYPE TEXT,
        CRASH_TYPE TEXT,
        DAMAGE TEXT,
        DATE_POLICE_NOTIFIED TEXT,
        PRIM_CONTRIBUTORY_CAUSE TEXT,
        SEC_CONTRIBUTORY_CAUSE TEXT,
        STREET_NO INTEGER,
        STREET_DIRECTION TEXT,
        STREET_NAME TEXT,
        BEAT_OF_OCCURRENCE DOUBLE,
        NUM_UNITS INTEGER,
        MOST_SEVERE_INJURY TEXT,
        INJURIES_TOTAL DOUBLE,
        INJURIES_FATAL DOUBLE,
        INJURIES_INCAPACITATING DOUBLE,
        INJURIES_NON_INCAPACITATING DOUBLE,
        INJURIES_REPORTED_NOT_EVIDENT DOUBLE,
        INJURIES_NO_INDICATION DOUBLE,
        INJURIES_UNKNOWN DOUBLE,
        CRASH_HOUR BIGINT,
        CRASH_DAY_OF_WEEK BIGINT,
        CRASH_MONTH BIGINT,
        LATITUDE DOUBLE,
        LONGITUDE DOUBLE,
        LOCATION TEXT,
        date TEXT,
        year INTEGER
    );
""")

conn_sqlite.commit()

print("Table 'crash_data' created successfully in SQLite!")

Table 'crash_data' created successfully in SQLite!

In [ ]:
# Data Insertion
df.to_sql(
    "crash_data",
    conn_sqlite,
    if_exists="replace",
    index=False
)

print("Data inserted successfully!")

Data inserted successfully!

In [57]:
query = "SELECT COUNT(*) as total_rows FROM crash_data;"
result = pd.read_sql(query,conn_sqlite)

print(result)

   total_rows
0      660934

In [97]:
query = "SELECT * FROM crash_data LIMIT 5"

result = pd.read_sql(query, conn_sqlite)

display(result)

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date,year
0,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...,01/14/2025 12:25:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,2.0,0.0,12,3,1,41.997808,-87.655770,POINT (-87.655770494712 41.997807727633),2025-01-14 12:25:00,2025
1,027b0b4c21460d3441fd83929abb9673c6fc0c7d575675...,05/23/2025 09:30:00 AM,30,STOP SIGN/FLASHER,UNKNOWN,UNKNOWN,DAYLIGHT,TURNING,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,2.0,0.0,9,6,5,41.946529,-87.688106,POINT (-87.688106391039 41.946529480518),2025-05-23 09:30:00,2025
2,04d91dffc94f677358ca47056921ba5c4224320df27ed4...,04/05/2025 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,UNKNOWN,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,20,7,4,41.899325,-87.715074,POINT (-87.715074373867 41.899324573751),2025-04-05 20:00:00,2025
3,0b5603954d84b7341c7cad4f570ea039e85919f3750ccb...,05/23/2025 09:15:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,STRAIGHT AND LEVEL,...,2.0,0.0,9,6,5,41.902793,-87.699412,POINT (-87.699412181285 41.902792968177),2025-05-23 09:15:00,2025
4,00bce77960c2faa2a8782a8cac1d6e5715802d6c072a08...,01/14/2025 08:00:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,REAR END,FOUR WAY,STRAIGHT AND LEVEL,...,2.0,0.0,8,3,1,41.691207,-87.720555,POINT (-87.720554863466 41.691206664451),2025-01-14 08:00:00,2025